/* Sending it, and the three ways that goes wrong.
 *
 * The product's most consequential step, and until now the only one that could
 * not fail. Reading a statement had a failure state and writing to the general
 * ledger did not, which is exactly backwards: a bad read is recoverable by
 * asking for the file again, and a bad write is money in the wrong place.
 *
 * ---------------------------------------------------------------------------
 * What actually gets posted, and it is two things
 *
 * You do not post "the reconciliation". You post CORRECTING JOURNAL ENTRIES —
 * real GL entries with a debit, a credit, a date and a description, each one
 * generated by a resolution a person authorised — and CLEARED MARKS, a tick
 * against every ledger transaction that reached the bank this period.
 *
 * The distinction matters for failure. A rejected journal entry leaves the
 * books out of balance by that amount. A rejected cleared mark leaves a
 * transaction looking outstanding when it is not. Different problems, and the
 * screen has to be able to say which happened.
 *
 * ---------------------------------------------------------------------------
 * The idempotency key is the reason retry is safe
 *
 * It is derived from the reconciliation, the entry's own identity and nothing
 * else — not from a timestamp, not from an attempt number, not from a counter.
 * So the key for the same entry is the same key on the first attempt and the
 * fourth, and a retry after a connection dropped mid-batch cannot create a
 * second copy of something that already landed.
 *
 * That property is what turns "some of it went through and we do not know
 * which" from a crisis into a button. It is also worth SHOWING: a key printed
 * beside an entry is the difference between asking somebody to trust a retry
 * and letting them see why it is safe.
 *
 * Spec: docs/RECONCILER_PLAYBOOK.md Part 8 prompt 6, docs/FLOWS.md F5,
 * docs/TAXONOMY_AND_IA.md Part 7.
 */

import type { Match } from "@/lib/reconciliation/match";
import { proofAmount } from "@/lib/reconciliation/match";

export type EntryState = "waiting" | "sent" | "rejected";

export interface PostedEntry {
  id: string;
  /* Stable across attempts. See the header. */
  idempotencyKey: string;
  kind: "correcting-entry" | "cleared-mark";
  description: string;
  /* Correcting entries only. A cleared mark moves no money. */
  amount?: number;
  glAccount: string;
  state: EntryState;
  rejectedBecause?: string;
}

export type BatchState =
  | "posting"
  | "posted"
  | "partially-posted"
  | "post-failed"
  | "reversed";

export interface PostingBatch {
  id: string;
  period: string;
  attempt: number;
  entries: PostedEntry[];
  state: BatchState;
}

/* ---------- The key ---------- */

/* A short stable digest. Real keys are UUIDs the caller stores; what matters
 * for the design is that the SAME entry yields the SAME key every time, which a
 * pure function of its identity guarantees and a random value does not. */
function key(reconciliationId: string, entryId: string): string {
  let h = 2166136261;
  const s = `${reconciliationId}:${entryId}`;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return `idem_${(h >>> 0).toString(16).padStart(8, "0")}`;
}

/* ---------- Building the batch ---------- */

/* The entry a resolution produces, in the ledger's own language. The GL account
 * is where the other side of the entry lands: cash is already known, so what a
 * reviewer needs to see is the account the correction is going to. */
function glFor(m: Match): string {
  if (m.pattern?.id === "pattern-returned-payment") return "4010 · Rental income";
  const meaning = m.bankLines[0]?.typeMeaning ?? "";
  if (/interest/i.test(meaning)) return "4900 · Interest income";
  if (/fee|service|analysis/i.test(meaning)) return "5100 · Bank charges";
  return "4010 · Rental income";
}

export function buildBatch(
  reconciliationId: string,
  period: string,
  matches: Match[],
  attempt = 1
): PostingBatch {
  const entries: PostedEntry[] = [];

  /* 1 · correcting journal entries, one per authorised resolution */
  for (const m of matches) {
    if (m.resolution?.kind !== "add-correcting-entry") continue;
    entries.push({
      id: `entry-${m.id}`,
      idempotencyKey: key(reconciliationId, `entry-${m.id}`),
      kind: "correcting-entry",
      description:
        m.pattern?.confirmed
          ? m.pattern.label
          : m.bankLines[0]?.typeMeaning ?? "Correcting entry",
      amount: proofAmount(m),
      glAccount: glFor(m),
      state: "waiting",
    });
  }

  /* 2 · cleared marks, one per ledger transaction that reached the bank.
   *
   * A tick, not a journal entry. It moves no money and it is why the count on
   * the confirm is two numbers rather than one. */
  for (const m of matches) {
    const cleared =
      m.outcome === "matched" ||
      m.resolution?.kind === "add-correcting-entry";
    if (!cleared) continue;
    for (const row of m.ledgerRows) {
      entries.push({
        id: `mark-${row.id}`,
        idempotencyKey: key(reconciliationId, `mark-${row.id}`),
        kind: "cleared-mark",
        description: row.description,
        glAccount: "1010 · Operating cash",
        state: "waiting",
      });
    }
  }

  return {
    id: `batch-${reconciliationId}-${attempt}`,
    period,
    attempt,
    entries,
    state: "posting",
  };
}

/* ---------- What the far end does with them ---------- */

/* One entry the ledger refuses, deliberately and always the same one.
 *
 * A prototype where sending always succeeds is the exact defect being fixed
 * here, and a random failure would be worse than none: it cannot be
 * demonstrated, cannot be walked through, and turns a design decision into a
 * dice roll. So the first attempt rejects one entry for a reason a property
 * accountant would actually meet, and the retry succeeds.
 *
 * The bank-charges account being inactive for the entity is a real and dull
 * failure: somebody closed it in the chart of accounts and nothing downstream
 * knew. That is what most posting failures are. */
const ALWAYS_REJECTS = "5100 · Bank charges";
const REJECTION =
  "Yardi refused it: 5100 Bank charges is inactive for this entity. Somebody closed it in the chart of accounts.";

export function settleEntry(
  entry: PostedEntry,
  attempt: number
): PostedEntry {
  const rejects = attempt === 1 && entry.glAccount === ALWAYS_REJECTS;
  return rejects
    ? { ...entry, state: "rejected", rejectedBecause: REJECTION }
    : { ...entry, state: "sent" };
}

export function batchOutcome(entries: PostedEntry[]): BatchState {
  const sent = entries.filter((e) => e.state === "sent").length;
  const rejected = entries.filter((e) => e.state === "rejected").length;
  if (rejected === 0) return "posted";
  if (sent === 0) return "post-failed";
  return "partially-posted";
}

/* ---------- Retry, and undo ---------- */

/* A retry re-sends ONLY what did not land, and every entry keeps the key it
 * already had. That is the whole safety argument made concrete: the entries
 * that succeeded are not in the batch, and if one of them somehow were, the far
 * end would recognise its key and do nothing. */
export function retryBatch(batch: PostingBatch): PostingBatch {
  return {
    ...batch,
    id: `${batch.id}-retry`,
    attempt: batch.attempt + 1,
    state: "posting",
    entries: batch.entries.map((e) =>
      e.state === "rejected"
        ? { ...e, state: "waiting", rejectedBecause: undefined }
        : e
    ),
  };
}

/* The strongest trust feature in the product, and the cheapest to build.
 *
 * It reverses what LANDED, which on a partial post is not the whole batch. The
 * entries that were rejected never reached the ledger, so reversing them would
 * be writing a correction for something that does not exist. */
export function reverseBatch(batch: PostingBatch): PostingBatch {
  return {
    ...batch,
    state: "reversed",
    entries: batch.entries.map((e) =>
      e.state === "sent" ? { ...e, state: "waiting" } : e
    ),
  };
}

export function counts(entries: PostedEntry[]) {
  return {
    total: entries.length,
    sent: entries.filter((e) => e.state === "sent").length,
    rejected: entries.filter((e) => e.state === "rejected").length,
    corrections: entries.filter((e) => e.kind === "correcting-entry").length,
    marks: entries.filter((e) => e.kind === "cleared-mark").length,
  };
}
